package NS_MINI_INTERFACE;

import com.tencent.mobileqq.pb.MessageMicro;
import com.tencent.mobileqq.pb.PBField;
import com.tencent.mobileqq.pb.PBInt32Field;
import com.tencent.mobileqq.pb.PBInt64Field;
import com.tencent.mobileqq.pb.PBStringField;

/**
 * Stub for QQ's mini-program interface messages.
 *
 * compileOnly: the real classes come from the host at runtime. Field names must
 * match the host verbatim, because the generated bytecode does getfield on them.
 * Only the fields actually touched are declared here - an omitted field is
 * harmless, a misspelled one is a NoSuchFieldError.
 */
public final class INTERFACE {

    public static final class StJudgeTimingReq extends MessageMicro<StJudgeTimingReq> {
        public final PBStringField appid = PBField.initString("");
        public final PBInt32Field factType = PBField.initInt32(0);
        public final PBInt32Field duration = PBField.initInt32(0);
        public final PBInt64Field reportTime = PBField.initInt64(0);
        public final PBInt32Field afterCertify = PBField.initInt32(0);
        public final PBInt32Field appType = PBField.initInt32(0);
        public final PBInt32Field scene = PBField.initInt32(0);
        public final PBInt32Field totalTime = PBField.initInt32(0);
        public final PBStringField launchId = PBField.initString("");
        public final PBStringField via = PBField.initString("");
        public final PBInt32Field AdsTotalTime = PBField.initInt32(0);
        public final PBStringField sourceID = PBField.initString("");
    }

    public static final class StJudgeTimingRsp extends MessageMicro<StJudgeTimingRsp> {
    }
}
